version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

  synchronizer:
    image: darchlabs/synchronizer-v2
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  backoffice:
    image: darchlabs/backoffice:0.0.2
    depends_on:
      - postgres_backoffice
    ports:
    - 9000:9000
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./data/backoffice:/home/backoffice/data
    environment:
      - ENVIRONMENT=dev
      - SECRET_KEY=this-is-secre-key
      - DB_DRIVER=postgres
      - DB_DSN=postgres://postgres:postgres@postgres_backoffice:5432/postgres?sslmode=disable
      - DB_MIGRATIONS_DIR=migrations/
      - API_SERVER_PORT=9000

  postgres_backoffice:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
