version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin


  synchronizer:
    image: darchlabs/synchronizer-v2
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
