version: "3.9"

volumes:
  data-postgres:
    driver: local
  data-redis:
    driver: local

services:
  synchronizer:
    image: synchronizer
    ports:
      - 5555:5555
    env_file:
      - .env
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-postgres:/data-postgres
