version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  synchronizer:
    image: darchlabs/synchronizer-v2
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
