sequenceDiagram
    Synchronizer->>+Event: NewStorage(path)
    Event-->>-Synchronizer: 
    Synchronizer->>+EthClient: Dial(url)
    EthClient-->>-Synchronizer: 
    Synchronizer->>+Cronjob: NewCronJob(seconds,storage,client)
    Cronjob-->>-Synchronizer: 
    Synchronizer->>+API: Initialize API
    API-->>-Synchronizer: 
    Synchronizer->>+Event: Initialize router with EventStorage
    Event-->>-Synchronizer: 
    Synchronizer->>+Cronjob: Initialize router
    Cronjob-->>-Synchronizer: 
    Synchronizer->>+Cronjob: Start()
    Cronjob-->>-Synchronizer: 
    Synchronizer->>+API: Listen(port)
    API-->>-Synchronizer: 
    Synchronizer->>+OS: Listen SIGNTERM signal
    OS-->>-Synchronizer: 